# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# Reference: https://www.appveyor.com/docs/appveyor-yml/

#-----------------------------------#
# Configuration for master branch  #
# Build and publish artifacts       #
#-----------------------------------#
-
  branches:
    only:
      - master

  # version format
  version: '1.1.{build}'

  # Do not build on tags (GitHub and BitBucket)
  skip_tags: true

  # Build worker image (VM template)
  image: Visual Studio 2017

  # build Configuration, i.e. Debug, Release, etc.
  configuration: Release

  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'

  before_build:
    - dotnet restore

  build:
    project: 'src\Microsoft.Hadoop.Avro\Microsoft.Hadoop.Avro.csproj'
    publish_nuget: true

  deploy:
    provider: NuGet
    server:                  # remove to push to NuGet.org
    api_key:
      secure: 7hCXGI9g/S/3iu00/OvfdiEJVLcQjSzpx6lB+5qsyvs6iLD6oFCQ8NzcRs7wg2bO
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/

#------------------------------------------------------------#
# Configuration for feature branches                         #
# Just build and run unit tests without publishing artifacts #
#------------------------------------------------------------#
-
  # version format
  version: '1.0.{build}'

  # Do not build on tags (GitHub and BitBucket)
  skip_tags: true

  # Build worker image (VM template)
  image: Visual Studio 2017

  # build Configuration, i.e. Debug, Release, etc.
  configuration: Debug

  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'

  before_build:
    - dotnet restore

  build:
    project: 'src\Microsoft.Hadoop.Avro\Microsoft.Hadoop.Avro.csproj'

  notifications:
    - provider: GitHubPullRequest
      auth_token:
        # Auth token encrypted using: https://ci.appveyor.com/tools/encrypt
        secure: 4JA3V5gyY3iWMfl49Kd1p9F/doteIJlHkLhphqPFXpO0MCT3MR1gY09NI+PVEQju
